% following is for displaying
figure(9);
hold on;
plot(AV_adoption_rate, percent_curbside_all,'-*',...
    'Color', [50,205,50]/255,...
    'LineWidth',2,...
    'MarkerSize',10,...
    'MarkerEdgeColor',[50,205,50]/255,...
    'MarkerFaceColor',[50,205,50]/255);
plot(AV_adoption_rate, percent_private_parking_all,'-o',...
    'Color', [250,128,114]/255,...
    'LineWidth',2,...
    'MarkerSize',10,...
    'MarkerEdgeColor',[250,128,114]/255,...
    'MarkerFaceColor',[250,128,114]/255);
legend('Curbside percentage','Private parking percentage');
xlabel('Autonomous vehicle market penetration');
ylabel('Parking/curbside percentage ');
% using '%' in y-axis
ystr=[cellstr(num2str(get(gca,'ytick')'*100))];
pct = char(ones(size(ystr,1),1)*'%');
new_yticks = [char(ystr),pct];
set(gca,'yticklabel',new_yticks)
% using % in x-axis
xstr=[cellstr(num2str(get(gca,'xtick')'*100))];
pct = char(ones(size(xstr,1),1)*'%');
new_xticks = [char(xstr),pct];
set(gca,'xticklabel',new_xticks) 

set(gca,'FontSize',16);
hold off;

figure(10);
plot(AV_adoption_rate, parking_revenue_all,'-^',...
    'Color', [30,144,255]/255,...
    'LineWidth',2,...
    'MarkerSize',10,...
    'MarkerEdgeColor',[30,144,255]/255,...
    'MarkerFaceColor',[30,144,255]/255)
xlabel('Autonomous vehicle market penetration');
ylabel('Airport revenue (dollars per day)');
% using % in x-axis
xstr=[cellstr(num2str(get(gca,'xtick')'*100))];
pct = char(ones(size(xstr,1),1)*'%');
new_xticks = [char(xstr),pct];
set(gca,'xticklabel',new_xticks) 

set(gca,'FontSize',16);